### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jgillich** [devilesk/interactive-dota-map#1]
I'm thinking about doing something similar (just a lot simpler, basically I just want some annotations, but don't want to use images). For this, I might want to reuse some of your code, but unfortunately there is no license. Can you please add one?

**Comment by devilesk** [comment]
I have added an MIT license.

**Comment by jgillich** [comment]
Thanks! Another thing, I hope you don't mind me asking, do you have a working movecam.cfg for reborn? I [tried](https://gist.github.com/jgillich/abb4008d05c1c8f6d051) to get it working again, but for whatever reason reborn just stops executing the config at some random location. Maybe they introduced some kind of file limit that I don't know about..

**Comment by devilesk** [comment]
No I don't, sorry. I haven't tried running it in reborn. They may not have ported some commands or maybe the coordinates are a little different. I know cl_leveloverview doesn't work last time I checked in reborn so I haven't tried taking any screenshots of the map.

**Comment by jgillich** [comment]
It does work, it's just that it stops somewhere around 300 because it can't find the rest of the aliases. I'll let you know when I figure it out. About the coordinates, did you calculate them somehow? There's very little information to be found about the map in general.

One thing I have to try is extracting the minimap from the [vpk](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Level_Design/Dota/Minimap). If its resolution is high enough, this silly scraping could be skipped entirely.
